version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.line-breaker
    volumes:
      - type: bind
        source: .
        target: /app
    command: sh -c "dos2unix **/*"
