enum WordTagEnum {
  AGRICULTURE = 'agriculture',
  ARTS = 'arts',
  BOTANY = 'botany',
  COMMERCE = 'commerce',
  EDUCATION = 'education',
  FASHION = 'fashion',
  FOOD = 'food',
  GEOGRAPHY = 'geography',
  KINSHIP = 'kinship',
  MARINE = 'marine',
  MATHEMATICS = 'mathematics',
  MEDICINE = 'medicine',
  CULTURE = 'culture',
  LANGUAGE = 'language',
  LAW = 'law',
  PERFORMING_ARTS = 'performing_arts',
  POLITICS = 'politics',
  RELIGION = 'religion',
  SPORTS = 'sports',
  TECHNOLOGY = 'technology',
  TRANSPORTATION = 'transportation',
  VISUAL_ARTS = 'visual_arts',
  WEATHER = 'weather',
  ZOOLOGY = 'zoology',
}

export default WordTagEnum;
